config/routes.rb
Rails.application.routes.draw do

  # Authentication
  devise_for :users#, controllers: { omniauth_callbacks: 'omniauth' }

  # Pages Controller
  root to: "pages#home"
  get "/about", to: "pages#about"
  
  # Listings Controller
  resources :listings
  get "/user/:id/listings", to: "listings#all", as: "user_listings"

  # Profiles
  get "/user/profile/new", to: "profiles#new"
  post "/user/profile/new", to: "profiles#create"
  get "/user/profile/show", to: "profiles#show"
  get "/user/profile/:id/view", to: "profiles#view", as: "user_profile_view"
  put "/user/profile/show", to: "profiles#update"
  
  # Sales and purchases
  get "/user/sales", to: "transactions#sales"
  get "/user/purchases", to: "transactions#purchases"

  # Messaging system
  resources :conversations do
    resources :messages
  end

  # Cart
  get "/cart", to: "carts#index"
  put "/cart/:cart_id/:listing_id", to: "carts#add", as: "cart_add"
  put "/cart/:cartlisting_id", to: "carts#update", as: "cart_update"
  delete "/cart/:cartlisting_id", to: "carts#delete", as: "cart_delete"

  # Transactions
  get "/checkout/success", to: "transactions#success"
  post "/checkout", to: "transactions#create"
  get "/checkout/cancel", to: "transactions#cancel"
  post "/payments/webhook", to: "transactions#webhook"

  # Search functionality
  get '/search' => 'pages#search', as: 'search_page'
  
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :bsb, presence: true
  validates :account, presence: true
  
  belongs_to :user
  has_one_attached :image
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :get_profile, only: %i[ show update new ]

    # Basic CRUD controller for user profiles

    def new
        # If a profile already exists, redirect to the profile. Or else create a new one
        if get_profile.present?
            redirect_to user_profile_show_path
        else
            @profile = Profile.new
        end
    end

    def create
        # A method to create a new profile
        @profile = Profile.new(permitted_params)
        @profile.user_id = current_user.id

        respond_to do |format|
            if @profile.save
              format.html { redirect_to user_profile_show_path, notice: "Successfully created profile." }
              format.json { render :show, status: :created }                
            else
              flash[:alert] = "There was an error in creating your profile."
              format.html { render user_profile_new_path, status: :unprocessable_entity }
              format.json { render json: @profile.errors, status: :unprocessable_entity }
            end
        end
    end

    def show
        # If a profile already exists, redirect to the profile. Or else create a new one
        if get_profile.present?
            @profile = get_profile
        else
            flash[:notice] = "Please create a profile below."
            redirect_to user_profile_new_path
        end
    end

    def view
        # Show profile if it exists, or else just redirect to own user profile
        if not current_user.profile.blank? and current_user.profile.id == params[:id].to_i
            redirect_to user_profile_show_path
        else
            @profile = Profile.find(params[:id])
        end
    end

    def update
        # A method to update the profile based on allowed params
        @profile = get_profile
        respond_to do |format|
            if @profile.update(permitted_params)    
                format.html { redirect_to user_profile_show_path, notice: "Profile was successfully updated." }
                format.json { render :show, status: :ok }
            else
              flash[:alert] = "There was an error in updating your profile."
              format.html { render :show, status: :unprocessable_entity }
              format.json { render json: @profile.errors, status: :unprocessable_entity }
            end
        end
    end

    private
        def get_profile
            current_user.profile
        end

        def permitted_params
            params.require(:profile).permit(:firstname, :lastname, :bsb, :account, :image)
        end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<!-- This is a simple CRUD form to update and show the user profile. -->

<div class="container w-9/12">
 
  <%= form_with(model: profile, url: url, method: method) do |form| %>
    
    <!-- Error Handling -->
    <% if profile.errors.any? %>
        <%= render "shared/error_handling", model: profile %>
    <% end %>

  <div class="border-b-2 block md:flex">

    
    <div class="w-full md:w-2/5 p-4 sm:p-6 lg:p-8 bg-white shadow-md">
    
      <div class="flex justify-between">
        <span class="text-xl font-semibold block">Your Profile</span>
      </div>
    
        <div class="w-full p-8 mx-2 flex justify-center">
          <label class='flex flex-col border-4 border-dashed w-full h-32 hover:bg-pink-100 hover:border-red-900 group'>
                <div class='flex flex-col cursor-pointer items-center justify-center pt-7'>
                    <!-- Check if an attached image exists -->
                    <% if profile.image.attached? %>
                        <%= image_tag url_for(profile.image), class: "w-32 -mt-14" %>
                    <% else %>
                        <i class="fas fa-images text-4xl text-red-900 group-hover:text-red-800"></i>
                        <p class='lowercase text-sm group-hover:text-gray-800 pt-1 tracking-wider'>Select a photo</p>
                    <% end %>
                </div>
            <%= form.file_field :image, class: "hidden" %>
          </label>                         
        </div>


        <!-- Display different buttons depending on whether the current user is the viewer of this page -->
        <!-- I wanted the current user to be able to view their own sales, purchases and listings -->
        <% profile_user = profile.user %>
        <% if (profile_user == current_user) %>
            <div class="flex justify-center pt-12">
                <div class="flex flex-wrap md:flex-nowrap gap-1">
                    <%= link_to "Manage Listings", user_listings_path(current_user.id), class: "grid place-items-center rounded-lg border px-3 py-2 hover:bg-red-800 hover:text-white transition" %>      
                    <%= link_to "View All Sales", user_sales_path, class: "grid place-items-center rounded-lg border px-3 py-2 hover:bg-red-800 hover:text-white transition" %>
                    <%= link_to "View All Purchases", user_purchases_path, class: "grid place-items-center rounded-lg border px-3 py-2 hover:bg-red-800 hover:text-white transition" %>
                </div>
            </div>
        <% else %>
            <div class="flex justify-center pt-12">
                <div class="flex flex-wrap md:flex-nowrap gap-1">
                  <% unless current_user.profile.blank? %>
                    <%= link_to "View Listings", user_listings_path(profile_user) , class: "grid place-items-center rounded-lg border px-3 py-2 hover:bg-red-800 hover:text-white transition" %>
                  <% end %>
                </div>
            </div>
        <% end %>
    </div>
 
    <div class="w-full md:w-3/5 p-8 bg-white lg:ml-4 shadow-md">
      <div class="rounded  shadow p-6">
        
        <div class="pb-6">
          <%= form.label :firstname, "First Name:", class: "font-semibold text-gray-700 block pb-1" %>
          <div class="flex">
            <%= form.text_field :firstname, class: "border-1 rounded-r px-4 py-2 w-full" %>
          </div>
        </div>

        <div class="pb-6">
          <%= form.label :lastname, "Last Name:", class: "font-semibold text-gray-700 block pb-1" %>
          <div class="flex">
            <%= form.text_field :lastname, class: "border-1 rounded-r px-4 py-2 w-full" %>
          </div>
        </div>

        <div class="pb-6">
          <%= form.label :bsb, "BSB:", class: "font-semibold text-gray-700 block pb-1" %>
          <div class="flex">
            <%= form.text_field :bsb, class: "border-1 rounded-r px-4 py-2 w-full", maxlength: 6, autocomplete: 'off' %>
          </div>
        </div>

        <div class="pb-6">
          <%= form.label :account, "Account:", class: "font-semibold text-gray-700 block pb-1" %>
          <div class="flex">
            <%= form.text_field :account, class: "border-1 rounded-r px-4 py-2 w-full", autocomplete: 'off' %>
          </div>
        </div> 

        <div class="pb-4">
        
          <label for="about" class="font-semibold text-gray-700 block pb-1">Email: </label>
          <input disabled id="email" class="border-1  rounded-r px-4 py-2 w-full" type="email" value="<%= current_user.email %>" />
          <span class="text-gray-600 pt-4 block opacity-70">To change your e-mail, <%= link_to "go here", edit_user_registration_path, class: "text-red-800 hover:underline" %>. If you would like to change your password, <%= link_to "click here", edit_user_password_path, class: "text-red-800 hover:underline" %> </span>
        </div>

        <div class="pb-6">
          <%= form.submit ((params[:action]=="show") ? "Update Profile" : "Create Profile"), class: "w-auto bg-red-900 hover:bg-red-800 rounded-lg shadow-xl font-medium text-white px-4 py-2" %>
        </div>
        
      </div>
    <% end %>
    </div>

  </div>
 
</div>

app/views/profiles/new.html.erb
<%= render "form", profile: @profile, method: :post, url: user_profile_new_path %>

app/views/profiles/show.html.erb
<!-- The name "show" here is misleading because the user can edit their own profile on the show page. The correct page name would have been "edit", but I left it as is. -->

<%= render "form", profile: @profile, method: :put, url: user_profile_show_path %>

app/views/profiles/view.html.erb
<div class="container w-9/12">
  <div class="border-b-2 block md:flex">
    <div class="w-full md:w-2/5 p-4 sm:p-6 lg:p-8 bg-white shadow-md">
      <div class="flex justify-between">
        <span class="text-xl font-semibold block"><%= @profile.firstname.capitalize %>'s Profile</span>
      </div>
    
        <div class="w-full p-8 mx-2 flex justify-center">
                <div class='flex flex-col cursor-pointer items-center justify-center pt-7'>
                    <!-- Check if image attached -->
                    <% if @profile.image.attached? %>
                        <%= image_tag url_for(@profile.image), class: "w-32 -mt-14" %>
                    <% end %>
                    </div>
        </div>

          <% profile_user = @profile.user %>
          <div class="flex justify-center pt-12">
                <div class="flex flex-wrap md:flex-nowrap gap-1">
                    <%= link_to "View Listings", user_listings_path(profile_user), class: "grid place-items-center rounded-lg border px-3 py-2 hover:bg-red-800 hover:text-white transition" %>
                </div>
          </div>

          <div class="flex justify-center pt-12">

          <!-- Display different buttons depending on whether the current user is the viewer of this page -->
              <% unless profile_user == current_user %>
                <div class="flex flex-wrap md:flex-nowrap gap-1">
                <%= link_to 'Message me', conversations_path(sender_id: current_user.id, recipient_id: @profile.user.id), method: 'post', class: "grid place-items-center rounded-lg border px-3 py-2 hover:bg-red-800 hover:text-white transition" %>
                </div>
              <% end %>
          </div>
    </div>
 
    <div class="w-full md:w-3/5 p-8 bg-white lg:ml-4 shadow-md">
      <div class="rounded  shadow p-6">

        <!-- The user needs to be able to see first name, last name and email, but not bank account details -->
        
        <div class="pb-6">
          <div class="font-semibold text-gray-700 block pb-1">First Name:</div>
          <div class="flex">
            <%= @profile.firstname %>
          </div>
        </div>

        <div class="pb-6">
          <div class="font-semibold text-gray-700 block pb-1">Last Name:</div>
          <div class="flex">
            <%= @profile.lastname %>
          </div>
        </div>

        <div class="pb-4">
          <div class="font-semibold text-gray-700 block pb-1">Email:</div>
          <div class="flex">
            <%= @profile.user.email %>
          </div>
        </div>
      </div>
    </div>

  </div>
 
</div>