config/routes.rb
Rails.application.routes.draw do

  # Authentication
  devise_for :users#, controllers: { omniauth_callbacks: 'omniauth' }

  # Pages Controller
  root to: "pages#home"
  get "/about", to: "pages#about"
  
  # Listings Controller
  resources :listings
  get "/user/:id/listings", to: "listings#all", as: "user_listings"

  # Profiles
  get "/user/profile/new", to: "profiles#new"
  post "/user/profile/new", to: "profiles#create"
  get "/user/profile/show", to: "profiles#show"
  get "/user/profile/:id/view", to: "profiles#view", as: "user_profile_view"
  put "/user/profile/show", to: "profiles#update"
  
  # Sales and purchases
  get "/user/sales", to: "transactions#sales"
  get "/user/purchases", to: "transactions#purchases"

  # Messaging system
  resources :conversations do
    resources :messages
  end

  # Cart
  get "/cart", to: "carts#index"
  put "/cart/:cart_id/:listing_id", to: "carts#add", as: "cart_add"
  put "/cart/:cartlisting_id", to: "carts#update", as: "cart_update"
  delete "/cart/:cartlisting_id", to: "carts#delete", as: "cart_delete"

  # Transactions
  get "/checkout/success", to: "transactions#success"
  post "/checkout", to: "transactions#create"
  get "/checkout/cancel", to: "transactions#cancel"
  post "/payments/webhook", to: "transactions#webhook"

  # Search functionality
  get '/search' => 'pages#search', as: 'search_page'
  
end

app/models/listing.rb
class Listing < ApplicationRecord
  validates :name, length: { minimum: 2 }
  validates :description, length: { maximum: 500 }
  validates :price, numericality: true
  validates :vintage, numericality: true
  validates :category_id, presence: true
  validates :region_id, presence: true
  validates :image, presence: true

  belongs_to :user
  belongs_to :category
  belongs_to :region
  has_one_attached :image

  has_many :cart_listings, dependent: :destroy
  has_many :carts, through: :cart_listings
  # has_many :carts, through: :cart_listings, dependent: :destroy
  # has_and_belongs_to_many :cart_listings, dependent: :destroy
  # has_and_belongs_to_many :transactions # If issues persist, delete this line

  after_create do
    product = Stripe::Product.create(name: name)
    price = Stripe::Price.create(product: product, unit_amount: self.price, currency: 'aud')
    update(stripe_product_id: product.id, stripe_price_id: price.id)
  end

  def to_s  # Just so that listing.name does not have to be typed in every time
    name
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :listing_find, only: [:show, :edit, :update, :delete]

    def index
        # Show all listings on website
        @listings = Listing.all
    end

    def show
    end

    def new
        # In order to sell an item, the seller must have a profile. This method redirects
        # the user to the profile creation page where users can create a profile
        unless current_user.profile.present?
            flash[:alert] = "You must create a seller profile before you can list items for sale."
            redirect_to user_profile_new_path
        else
            @listing = Listing.new
            # if params[:q]
            #     @results = GoogleCustomSearchApi.search(params[:q], page: 1)
            # end
        end
    end

    def create      # Create a new listing
        @listing = Listing.new(listing_params)

        # Set price in cents by multiplying by 100
        @listing.price = params[:listing][:price].to_i * 100
        @listing.user_id = current_user.id

        # Save listing
        respond_to do |format|
            if @listing.save
                format.html { redirect_to listing_path(@listing.id), notice: "Successfully created listing." }
                format.json { render :show, status: :created }
            else
                flash[:alert] = "Unable to create listing at this time."
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @listing.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit
        # Divide price by cents to get dollar figure
        @listing.price /= 100
    end

    def update
        # Authorisation from Pundit
        authorize @listing
        @listing.assign_attributes(listing_params)

        # Convert price to cents
        @listing.price = params[:listing][:price].to_i * 100

        # Update listing
        respond_to do |format|
            if @listing.save
              format.html { redirect_to listing_path(@listing.id), notice: "Successfully updated listing." }
              format.json { render :show, status: :ok }
            else
              flash[:alert] = "There was an error in updating your listing."
              format.html { render :show, status: :unprocessable_entity }
              format.json { render json: @listing.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy      # Delete listing
        if Listing.destroy(@listing.id)
            flash[:notice] = "Listing was successfully deleted"
            redirect_to listings_path
        else
            flash[:alert] = "Failed to delete listing"
            redirect_to request.referrer
        end
    end

    def all
        # Display all the users' listings
        # raise params.inspect
        @listings = Listing.where(user_id: params[:id])
        pp @listings
    end

    # No longer used
    # def scrape
    #     if params[:q]
    #       page = params[:page] || 1
    #       @results = GoogleCustomSearchApi.search(params[:q],
    #                                               page: page)
    #                                               pp GoogleCustomSearchApi.search(params[:q],
    #                                               page: page)                            
    #     end
    #     render :new
    # end

    private
        def listing_params
            params.require(:listing).permit(:name, :vintage, :category_id, :region_id, :description, :price, :image)
        end

        def listing_find
            @listing = Listing.find(params[:id])
        end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<!-- This is a simple CRUD form for the wine listings. Users can create, read, update and delete their wine lisings -->

<div class="flex justify-center my-6">
    <div class="flex flex-col w-full p-8 rounded-lg text-gray-800 bg-white bg-opacity-20 shadow-lg pin-r pin-y md:w-4/5 lg:w-4/5">

    <%= form_with(model: listing) do |form| %>

        <!-- Error Handling -->
        <% if listing.errors.any? %>
            <%= render "shared/error_handling", model: listing %>
        <% end %>

        <div class="flex">
            <div class="grid w-11/12 md:w-9/12 lg:w-1/2">
                <div class="flex justify-center py-4">
                    <div class="flex bg-red-200 rounded-full md:p-4 p-2 border-2 border-purple-300">
                    <i class="fas fa-wine-glass-alt"></i>
                    </div>
                </div>

                <div class="flex justify-center">
                    <h1 class="text-red-900 font-bold md:text-2xl text-xl"><%= local_assigns[:heading] %></h1>
                </div>

                <div class="grid grid-cols-1 mt-5 mx-7">
                    <%= form.label :name, "Name:", class: "uppercase md:text-sm text-xs text-light font-semibold" %>
                    <%= form.text_field :name, class: "py-2 px-3 rounded-lg border-2 border-red-200 mt-1 focus:outline-none focus:ring-2 focus:ring-red-800 focus:border-transparent", placeholder: "Example: Frogmore Creek Iced Riesling 375mL" %>
                </div>

                <div class="grid grid-cols-1 mt-5 mx-7">
                    <%= form.label :region_id, "Region:", class: "uppercase md:text-sm text-xs text-light font-semibold" %>
                    <%= form.select :region_id, Region.pluck(:name, :id), class: "py-2 px-3 rounded-lg border-2 border-red-200 mt-1 focus:outline-none focus:ring-2 focus:ring-red-800 focus:border-transparent" %>
                </div>

                <div class="grid grid-cols-1 mt-5 mx-7">
                    <%= form.label :vintage, "Vintage (Year):", class: "uppercase md:text-sm text-xs text-light font-semibold" %>
                    <%= form.number_field :vintage, class: "py-2 px-3 rounded-lg border-2 border-red-200 mt-1 focus:outline-none focus:ring-2 focus:ring-red-800 focus:border-transparent", placeholder: "Example: 2012" %>
                </div>

                <div class="grid grid-cols-1 mt-5 mx-7">
                    <%= form.label :category_id, "Wine Category:", class: "uppercase md:text-sm text-xs text-light font-semibold" %>
                    <%= form.select :category_id, Category.pluck(:name, :id), class: "py-2 px-3 rounded-lg border-2 border-red-200 mt-1 focus:outline-none focus:ring-2 focus:ring-red-800 focus:border-transparent" %>
                </div>

                <div class="grid grid-cols-1 mt-5 mx-7">
                    <%= form.label :description, "Description:", class: "uppercase md:text-sm text-xs text-light font-semibold" %>
                    <%= form.text_area :description, class: "py-2 px-3 rounded-lg border-2 border-red-200 mt-1 focus:outline-none focus:ring-2 focus:ring-pink-800 focus:border-transparent", placeholder: "Example: A savoury ice wine" %>
                </div>

                <div class="grid grid-cols-1 mt-5 mx-7">
                    <%= form.label :price, "Price (AUD $):", class: "uppercase md:text-sm text-xs text-light font-semibold" %>
                    <%= form.number_field :price, class: "py-2 px-3 rounded-lg border-2 border-red-200 mt-1 focus:outline-none focus:ring-2 focus:ring-pink-800 focus:border-transparent", step: 0.01, placeholder: "Example: 2012" %>
                </div>


                <div class="grid grid-cols-1 mt-5 mx-7">
                    <%= form.label "Upload Photo", class: "uppercase md:text-sm text-xs text-light font-semibold mb-1" %>
                    <div class='flex items-center justify-center w-full'>
                        <label class='flex flex-col border-4 border-dashed w-full h-32 hover:bg-pink-100 hover:border-red-900 group'>
                            <div class='flex flex-col cursor-pointer items-center justify-center pt-7'>
                                <% if @listing.image.attached? %>
                                    <%= image_tag url_for(@listing.image), class: "-mt-14", style: "object-fit: contain; max-width: 8rem; max-height: 8rem;" %>
                                <% else %>
                                    <i class="fas fa-images text-4xl text-red-900 group-hover:text-red-800"></i>
                                    <p class='lowercase text-sm group-hover:text-gray-800 pt-1 tracking-wider'>Select a photo</p>
                                <% end %>
                            </div>
                        <%= form.file_field :image, class: "hidden" %>
                        </label>
                    </div>
                </div>

                <div class='flex items-center justify-center  md:gap-8 gap-4 pt-5 pb-5'>
                    <%= link_to(button_tag("Cancel", class: "w-auto bg-gray-500 hover:bg-gray-700 rounded-lg shadow-xl font-medium text-white px-4 py-2"), :back)  %>
                    <%= form.submit(class: "w-auto bg-red-900 hover:bg-red-800 rounded-lg shadow-xl font-medium text-white px-4 py-2" ) %>
                </div>
            </div>
        </div>
    <% end %>
  </div>
</div>

app/views/listings/all.html.erb
<!-- This file displays the user his/her own listings on the website. It is fully responsive. -->

<h1 class="ml-0 md:ml-40 sm:ml-10 text-center text-red-900 sm:text-left pt-16 text-2xl font-bold antialiased">Your Listings</h1>
<div class="ml-0 md:ml-40 sm:ml-10 text-center sm:text-left pt-16 antialiased">
<%= link_to 'Create New Listing', new_listing_path, class: "w-auto bg-red-900 hover:bg-red-800 rounded-lg shadow-xl font-medium text-white px-4 py-2" %>
</div>
<div class="flex justify-center my-6">

    <div class="flex flex-col w-full p-8 rounded-lg text-gray-800 bg-white bg-opacity-20 shadow-lg pin-r pin-y md:w-4/5 lg:w-4/5">
        <div class="flex-1">
        
            <table class="w-full text-sm lg:text-base" cellspacing="0">
                <thead>
                    <tr class="h-12 uppercase">
                        <th class="hidden md:table-cell"></th>
                        <th class="text-left">Product</th>
                        <th class="lg:text-right text-left pl-5 lg:pl-0">
                            <span class="lg:hidden" title="Quantity">Ctgy</span>
                            <span class="hidden lg:inline">Category</span>
                        </th>
                        <th class="hidden text-right md:table-cell">Price</th>
                        <th class="text-right">Listed At</th>
                    </tr>
                </thead>

                <tbody>
                    <% if @listings.length == 0 %>
                        <tr><td></td><td class="hidden pb-4 md:table-cell">
                        <% if current_user.id == params[:id].to_i %>
                            You have no listings at the moment. You can <%= link_to "create a listing", new_listing_path, class: "text-red-800 hover:underline" %> here.</td></tr>
                        <% else %>
                            This user currently has no listings.
                        <% end %>
                    <% else %>
                        <% @listings.each do |listing| %>
                            <tr>
                                <td class="hidden pb-4 md:table-cell"> <%= link_to(image_tag(url_for(listing.image), class: "w-20 h-20 rounded ", style: "object-fit: contain; max-width: 5rem; max-height: 5rem;" , alt:
                                        listing), listing_path(listing.id), target: :_blank) %> </td>
                                <td>
                                    <p class="mb-2 md:ml-4"><%= link_to listing, listing_path(listing.id), target: :_blank, class: "hover:text-red-800" %></p>
                                    <% if current_user.id == params[:id].to_i %>
                                        <%= link_to(button_tag("<small><i class='fas fa-trash-alt w-4 text-red-600  hover:text-red-800'></i> Remove item</small>".html_safe, class:'text-gray-700 md:ml-4 hover:text-red-800'), listing_path(listing), method: "delete", data: { confirm: 'Are you sure you want to remove this item?' }) %>
                                    <% end %>
                                </td>
                                <td class="justify-center md:justify-end md:flex mt-6">
                                    <div class="w-20 h-10">
                                        <div class="relative flex flex-row w-full h-8">
                                            <%= Category.find(listing.category.id) %>
                                        </div>
                                    </div>
                                </td>
                                <td class="hidden text-right md:table-cell">
                                    <span class="text-sm lg:text-base font-medium"><%= number_to_currency(listing.price/100) %></span>
                                </td>

                                <td class="hidden text-right md:table-cell">
                                    <span class="text-sm lg:text-base"><%= listing.created_at.strftime("%d-%b-%Y %l:%M %p") %></span>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/listings/edit.html.erb
<%= render "form", heading: "Edit Listing", listing: @listing %>

app/views/listings/index.html.erb
<h1 class="ml-0 md:ml-40 sm:ml-10 text-center sm:text-left pt-16 text-2xl font-bold antialiased">Browse Catalog</h1>

<!-- I used several partials here to construct the listings index page and search page -->

<%= render "shared/searchbar" %>

<%= render "shared/searchresults" %>

app/views/listings/new.html.erb
<%= render "form", heading: "Create New Listing", listing: @listing %>

app/views/listings/show.html.erb
<!-- A simple display page to display the listing. It changes depends on who is signed in. If the listing's owner is signed in, he/she can edit or delete the listing. If anybody else is signed in, they can add it to cart. If no one is signed in, they can only view the listing. -->

<main class="grid place-items-center h-screen">
  <%= link_to "Back", :back %>
  <section class="flex flex-col md:flex-row gap-11 py-10 px-5 bg-white rounded-md shadow-lg w-3/4 md:max-w-2xl">
    <div class="text-red-800 flex flex-col justify-between">
      <% if @listing.image.attached? %>
        <%= image_tag url_for(@listing.image) %>
      <% end %>
      <% if (@listing.user == current_user) %>
        <div class="flex justify-center pt-12">
          <div class="flex flex-wrap md:flex-nowrap gap-1">
            <%= link_to "Edit Listing", edit_listing_path(@listing.id), method: "get", class: "grid place-items-center rounded-lg border px-3 py-2 hover:bg-red-800 hover:text-white transition" %>      
            <%= link_to "Delete Listing", listing_path(@listing.id), method: "delete", data: {confirm: "Are you sure you want to delete this listing? This action cannot be undone."}, class: "grid place-items-center rounded-lg border px-3 py-2 hover:bg-red-800 hover:text-white transition" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="text-red-800">
      <small class="uppercase"><%= Category.find(@listing.category_id) %></small>
      <h3 class="uppercase text-black text-2xl font-medium"><%= @listing %></h3>
      <h3 class="text-2xl font-semibold mb-7"><%= number_to_currency(@listing.price/100) %></h3>
      <small class="text-black"><%= @listing.description %></small>
      <p class="pt-4">Vintage: <%= @listing.vintage %></p>
      <small>(Actual vintages may vary)</small>
      <%  if (@listing.user != current_user and user_signed_in?) %>
        <div class="flex gap-0.5 mt-4">
            <%= link_to(button_tag("add to cart", id: "addToCartButton", class: "bg-red-900 hover:bg-red-700 focus:outline-none transition text-white rounded-lg uppercase px-8 py-3"), cart_add_path(current_user.cart.id, @listing.id), method: "put") %>
        </div>
        <div class="py-2 text-center h-16 font-bold tracking-wide text-gray-800">
            Sold By: <%= link_to @listing.user.profile.firstname, user_profile_view_path(@listing.user.profile.id), class:"text-red-800 hover:text-red-600" %></div>
        <% end %>
    </div>
  </section>
</main>