config/routes.rb
Rails.application.routes.draw do

  # Authentication
  devise_for :users#, controllers: { omniauth_callbacks: 'omniauth' }

  # Pages Controller
  root to: "pages#home"
  get "/about", to: "pages#about"
  
  # Listings Controller
  resources :listings
  get "/user/:id/listings", to: "listings#all", as: "user_listings"

  # Profiles
  get "/user/profile/new", to: "profiles#new"
  post "/user/profile/new", to: "profiles#create"
  get "/user/profile/show", to: "profiles#show"
  get "/user/profile/:id/view", to: "profiles#view", as: "user_profile_view"
  put "/user/profile/show", to: "profiles#update"
  
  # Sales and purchases
  get "/user/sales", to: "transactions#sales"
  get "/user/purchases", to: "transactions#purchases"

  # Messaging system
  resources :conversations do
    resources :messages
  end

  # Cart
  get "/cart", to: "carts#index"
  put "/cart/:cart_id/:listing_id", to: "carts#add", as: "cart_add"
  put "/cart/:cartlisting_id", to: "carts#update", as: "cart_update"
  delete "/cart/:cartlisting_id", to: "carts#delete", as: "cart_delete"

  # Transactions
  get "/checkout/success", to: "transactions#success"
  post "/checkout", to: "transactions#create"
  get "/checkout/cancel", to: "transactions#cancel"
  post "/payments/webhook", to: "transactions#webhook"

  # Search functionality
  get '/search' => 'pages#search', as: 'search_page'
  
end

app/views/shared/_error_handling.html.erb
<!-- I used the same partial for all "error" handling and form validation handling -->

<div class="bg-red-50 p-4 rounded flex items-start text-red-600 my-4 shadow-lg max-w-xl mx-auto">
    <div class="text-lg">
        <svg xmlns="http://www.w3.org/2000/svg" class="fill-current w-5 pt-1" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm4.597 17.954l-4.591-4.55-4.555 4.596-1.405-1.405 4.547-4.592-4.593-4.552 1.405-1.405 4.588 4.543 4.545-4.589 1.416 1.403-4.546 4.587 4.592 4.548-1.403 1.416z"/></svg>
    </div>
    <div class=" px-3">
        <h3 class="text-red-800 font-semibold tracking-wider">
            <%= pluralize(model.errors.count, "error") %> prohibited this <%= model.class.to_s.downcase %> from being saved:
        </h3>
        <ul class="list-disc list-inside"><% model.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
    </div>
</div>

app/views/shared/_searchbar.html.erb
<!-- A partial that displays the search bar -->


<div class="w-full mx-auto rounded-xl p-10 text-gray-800 relative overflow-hidden min-w-80 max-w-7xl">
    <div class="relative mt-1">
        <%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-left') do %>  
            <%= search_field_tag :query, params[:query], class: "form-control w-full h-16 px-3 rounded mb-8 focus:outline-none focus:shadow-outline text-xl px-8 shadow-lg", placeholder: "Search..." %>
            <%= button_tag "<i class='fas fa-search'></i>".html_safe, class: "block w-7 h-7 text-center text-xl leading-0 absolute top-4 right-4 text-gray-400 focus:outline-none hover:text-gray-900 transition-colors", name: nil %>
        <% end %>
    </div>
</div>

app/views/shared/_searchresults.html.erb
<!-- A partial that displays search results in a "card" format -->
<!-- Depending on who is signed in, I want them to be able to do different things. -->
<!-- For example, a user cannot add an item they've listed to their own cart -->

<div class="z-50 flex flex-wrap justify-center sm:w-full md:w-full lg:w-4/5 xl:w-4/5">
  <% if @listings %>  
    <% @listings.each do |listing| %>
        <div class="flex flex-col justify-center bg-gray-100 items-center max-w-sm mx-auto my-8 cursor-pointer rounded transform hover:scale-110 duration-300 ease-in-out">
          <% if listing.image.attached? %>
            <%= link_to image_tag(listing.image, class: "bg-gray-100 rounded-lg shadow-lg", style: "object-fit: contain; max-width: 14rem; max-height: 14rem;"), listing_path(listing.id) %>
          <% end %>
            <% listing_user = listing.user %>
            <% listing_user_profile = listing_user.profile %>
            <div class="w-56 md:w-64 bg-white  shadow-lg rounded-lg overflow-hidden">
                <div class="py-2 text-center h-16 font-bold uppercase tracking-wide text-gray-800 hover:text-red-800"><%= link_to listing, listing_path(listing.id) %></div>
                <div class="py-2 text-center h-16 font-bold tracking-wide text-gray-800 hover:text-red-800"><%= link_to "Sold By: #{(listing_user == current_user) ? "You" : listing_user_profile.firstname}", user_profile_view_path(listing_user_profile.id) %></div>
                <div class="flex items-center justify-between py-2 px-3 bg-gray-400">
                    <h1 class="text-gray-800 font-bold "><%= number_to_currency(listing.price / 100) %></h1>
                    <% if (listing_user != current_user and user_signed_in?) %>
                      <%= form_tag(cart_add_path(current_user.cart.id, listing.id), :method => "put") do |form| %>
                        <%= button_tag "Add to cart", type: "submit", class: "bg-red-900 text-xs text-white px-2 py-1 font-semibold rounded uppercase disabled:bg-gray-200 hover:bg-red-800" %>
                      <% end %>
                    <% else %>
                      <%= link_to "View Listing", listing_path(listing.id), class: "bg-gray-900 text-xs text-white px-2 py-1 font-semibold rounded uppercase hover:bg-gray-800" %>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
  <% end %>
</div>