config/routes.rb
Rails.application.routes.draw do

  # Authentication
  devise_for :users#, controllers: { omniauth_callbacks: 'omniauth' }

  # Pages Controller
  root to: "pages#home"
  get "/about", to: "pages#about"
  
  # Listings Controller
  resources :listings
  get "/user/:id/listings", to: "listings#all", as: "user_listings"

  # Profiles
  get "/user/profile/new", to: "profiles#new"
  post "/user/profile/new", to: "profiles#create"
  get "/user/profile/show", to: "profiles#show"
  get "/user/profile/:id/view", to: "profiles#view", as: "user_profile_view"
  put "/user/profile/show", to: "profiles#update"
  
  # Sales and purchases
  get "/user/sales", to: "transactions#sales"
  get "/user/purchases", to: "transactions#purchases"

  # Messaging system
  resources :conversations do
    resources :messages
  end

  # Cart
  get "/cart", to: "carts#index"
  put "/cart/:cart_id/:listing_id", to: "carts#add", as: "cart_add"
  put "/cart/:cartlisting_id", to: "carts#update", as: "cart_update"
  delete "/cart/:cartlisting_id", to: "carts#delete", as: "cart_delete"

  # Transactions
  get "/checkout/success", to: "transactions#success"
  post "/checkout", to: "transactions#create"
  get "/checkout/cancel", to: "transactions#cancel"
  post "/payments/webhook", to: "transactions#webhook"

  # Search functionality
  get '/search' => 'pages#search', as: 'search_page'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= ApplicationHelper::app_name %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  
  <body class="<%= params[:action] %>">
  <!-- I created class names for the body tag so that background images could be added to different pages using CSS -->

    <!-- The navbar is my work of art and it is PURELY CSS BASED - NO JAVASCRIPT. 
          It is fully responsive and utilises a checkbox system to show and hide the menu on smaller screens -->
    <nav class="navbar flex fixed items-center justify-between flex-wrap lg:px-12 shadow">
      <div class="justify-center w-full pr-2 sm:flex sm:justify-between lg:w-auto sm:w-full lg:border-b-0 sm:pl-6 sm:pr-2 lg:pb-0">
          <div class="flex items-center flex-shrink-0 text-gray-800 mr-16">
              
              <!-- I stored the app_name in a variable in the ApplicationHelper module so that I didn't have to type it everywhere if I changed it. -->
              <span class="font-semibold hidden sm:block sm:text-lg text-white tracking-tight"><%= link_to ApplicationHelper::app_name, root_path %></span>
          </div>

          <!-- This label below acts as the crux of the navbar functionality -->
          <label for="navbar-toggle-cbox" id="navbar-toggle-label"><i class="fas fa-bars burger"></i></label>
      </div>

      <!-- The checkbox below controls the navbar on smaller screen sizes -->
      <input type="checkbox" id="navbar-toggle-cbox">
      <div class="menu w-full lg:block flex-grow lg:flex lg:items-center lg:w-auto lg:px-3 px-8">
      
          <div class="text-md font-bold text-gray-700 lg:flex-grow">
              <span class="dash"> 🍷 </span> 

              <%= link_to "Home", root_path, class: "block lg:inline-block hover:text-white px-4 rounded hover:bg-gray-500" %> <span class="dash text-white"> | </span>

              <%= link_to "Catalog <i class='fas fa-book-open'></i>".html_safe, listings_path, class: "block lg:inline-block hover:text-white px-4 rounded hover:bg-gray-500" %><span class="dash text-white"> | </span>

              <span class="dash text-white">
              <%= link_to "Sell A Wine", new_listing_path, class: "block lg:inline-block hover:text-white px-4 rounded hover:bg-gray-500" %> | </span>

              <span class="lg:hidden block">
                <%= link_to "Search", search_page_path, class: "block lg:inline-block hover:text-white px-4 rounded hover:bg-gray-500" %>
              </span>

              <% if user_signed_in? %>
                <%= link_to "My Account <i class='fas fa-user-circle'></i>".html_safe, user_profile_show_path, class: "block lg:inline-block hover:text-white px-4 rounded hover:bg-gray-500" %> <span class="dash text-white">
                 | </span>
                
                <!-- I wanted to display the number of unread messages on the screen and therefore I wrote this snippet of code to check the database on each page load to see whether the user has received any new messages -->
                <% unread_messages = Message.all.where(user_id: current_user.id, read: false) %>
                <% if unread_messages.count == 0 %>
                  <%= link_to "Messages <i class='far fa-envelope-open'></i>".html_safe, conversations_path, class: "block lg:inline-block hover:text-white px-4 rounded hover:bg-gray-500", title: "You have no unread messages" %><span class="dash text-white">
                <% else %>
                  <%= link_to "Messages <i class='far fa-envelope'></i> #{unread_messages.count}".html_safe, conversations_path, class: "block lg:inline-block hover:text-white px-4 rounded hover:bg-gray-500", title: "You have #{unread_messages.count} unread messages" %><span class="dash text-white">
                <% end %>

                 <span class="dash text-white">   | </span>
              <% end %>
            <%= link_to "About", about_path, class: "block lg:inline-block hover:text-white px-4 rounded hover:bg-gray-500" %>
            <span class="dash"> 🍷 </span>
          </div>

          <!-- The search bar here is live and utilises a database query functionality to search the database -->
          <span class="relative mx-auto text-gray-600 lg:block hidden">
            <%= form_tag(search_page_path, :method => "get") do %>
              <%= search_field_tag :query, params[:query], placeholder: "Search", class: "border-2 border-gray-300 bg-white h-10 pl-2 pr-8 rounded-lg text-sm focus:outline-none" %>
              <button type="submit" class="absolute right-0 top-0 mr-2">
                  <div class="text-gray-600 h-4 w-4 fill-current">
                    <i class="fas fa-search"></i>
                  </div>
              </button>
            <% end %>
          </span>

          <!-- The links below change depending on whether or not the user is signed in -->
          <div class="block sm:flex">
            <% if user_signed_in? %>
              <%= link_to "View Cart <i class='fas fa-shopping-cart'></i>".html_safe, cart_path, method: "get", class: "block text-md px-4 py-2 rounded text-gray-700 ml-2 font-bold hover:text-white hover:bg-gray-500" %>
              <%= link_to "Log Out", destroy_user_session_path, method: "delete", class: "block text-md px-4 py-2 rounded text-gray-700 ml-2 font-bold hover:text-white hover:bg-gray-500" %>
            <% else %>
              <%= link_to "Log In", new_user_session_path, class: "block text-md px-4 py-2 rounded text-gray-700 sm:ml-2 ml-0 font-bold hover:text-white hover:bg-gray-500" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "block text-md px-4 py-2 rounded text-gray-700 sm:ml-2 ml-0 font-bold hover:text-white hover:bg-gray-500" %> 
            <% end%>
          </div>
        </div>
    </nav>
    
    <!-- I created separate section for notices which can be 'closed'. This also utilises a similar checkbox functionality as the navbar. -->
    <div class="notices">

      <% if flash[:notice] %>
        <input type="checkbox" id="hide-flash" class="hidden">
        <div class="space-x-2 bg-green-50 p-4 rounded flex items-center text-green-600 my-4 shadow-lg mx-auto max-w-2xl w-full">
          <div><i class="fas fa-check-circle"></i></div>
          <h3 class="text-green-800 tracking-wider flex-1"> <%= flash[:notice] %> </h3>
          <label for="hide-flash" class="inline-flex cursor-pointer items-center hover:bg-green-100 border border-green-50 hover:border-green-300 hover:text-green-900 focus:outline-none rounded-full p-2 hover:cursor-pointer">
              <input type="checkbox" id="hide-flash" class="hidden"><i class="fas fa-times-circle"></i>
          </label>
        </div>
      <% elsif flash[:alert] %>
        <input type="checkbox" id="hide-flash" class="hidden">
        <div class="space-x-2 bg-red-50 p-4 rounded flex items-center text-red-600 my-4 shadow-lg mx-auto max-w-2xl w-full">
          <div><i class="fas fa-times"></i></div>
          <h3 class="text-red-800 tracking-wider flex-1"> <%= flash[:alert] %> </h3>
          <label for="hide-flash" class="inline-flex cursor-pointer items-center hover:bg-red-100 border border-red-50 hover:border-red-300 hover:text-red-900 focus:outline-none rounded-full p-2 hover:cursor-pointer"> <i class="fas fa-times-circle"></i></label>
        </div>
      <% end %>
    </div>
    
    <%= yield %>

  </body>
</html>